"""Encode an image file into a base64 data URI and write it as a Python constant
(agent/demo_image.py) that the Image gallery demo imports.

Baking the data URI into code guarantees it ships with the agent package (a raw
file under assets/ may not be included by Agent Engine's extra_packages). GE also
blocks external image URLs and 500s on failed fetches, so an embedded data URI is
the reliable way to render an image.

Usage:
    python encode_image.py assets/demo.png
    python encode_image.py path/to/your-logo.jpg

Keep the image small (a few KB) — it becomes part of every Image-demo payload.
"""
import base64
import os
import sys

MIME = {"png": "png", "jpg": "jpeg", "jpeg": "jpeg", "gif": "gif", "webp": "webp"}


def main(path: str) -> None:
    ext = os.path.splitext(path)[1].lower().lstrip(".")
    if ext not in MIME:
        raise SystemExit(f"Unsupported image type: .{ext} (use {', '.join(MIME)})")
    with open(path, "rb") as f:
        data = f.read()
    b64 = base64.b64encode(data).decode("ascii")
    uri = f"data:image/{MIME[ext]};base64,{b64}"
    out = os.path.join(os.path.dirname(__file__), "agent", "demo_image.py")
    with open(out, "w", encoding="utf-8") as f:
        f.write(
            '"""Auto-generated by encode_image.py — do not edit by hand.\n'
            f'Source image: {os.path.basename(path)} ({len(data)} bytes)."""\n\n'
            f'DEMO_IMAGE_DATA_URI = "{uri}"\n'
        )
    print(f"wrote {out} from {path} ({len(data)} bytes, data URI {len(uri)} chars)")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit("usage: python encode_image.py <image-path>")
    main(sys.argv[1])
